"""M0 data-quality report generator.

Every number in the emitted markdown is the direct output of a SQL query
executed against the ingested database at generation time. Output is fully
deterministic for a given database state (all queries carry ORDER BY).
"""

from __future__ import annotations

import psycopg

from ingest.formats_config import load_formats


def _rows(conn: psycopg.Connection, sql: str) -> list[tuple]:
    with conn.cursor() as cur:
        cur.execute(sql)
        return list(cur.fetchall())


def _table(headers: list[str], rows: list[tuple]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out.extend("| " + " | ".join(str(c) for c in r) + " |" for r in rows)
    return "\n".join(out)


def generate_report(conn: psycopg.Connection, title_date: str) -> str:
    s: list[str] = [f"# M0 data-quality report — {title_date}", ""]
    s.append(
        "All numbers below are the printed output of SQL executed against the "
        "rebuilt database. Generated by `validation/m0_corpus/report.py`."
    )

    s.append("\n## Row counts\n")
    rows = _rows(
        conn,
        """
        SELECT relname, n FROM (
            SELECT 'games' AS relname, count(*) AS n FROM games UNION ALL
            SELECT 'formats', count(*) FROM formats UNION ALL
            SELECT 'cards', count(*) FROM cards UNION ALL
            SELECT 'events', count(*) FROM events UNION ALL
            SELECT 'decks', count(*) FROM decks UNION ALL
            SELECT 'deck_cards', count(*) FROM deck_cards UNION ALL
            SELECT 'matches', count(*) FROM matches UNION ALL
            SELECT 'archetypes', count(*) FROM archetypes UNION ALL
            SELECT 'archetype_labels', count(*) FROM archetype_labels UNION ALL
            SELECT 'ingest_unresolved_cards', count(*) FROM ingest_unresolved_cards
        ) t ORDER BY relname
        """,
    )
    s.append(_table(["table", "rows"], rows))

    s.append("\n## Events and decks by year x source\n")
    rows = _rows(
        conn,
        """
        SELECT extract(year FROM e.date)::int AS year, e.source,
               count(DISTINCT e.id) AS events, count(d.id) AS decks
        FROM events e LEFT JOIN decks d ON d.event_id = e.id
        GROUP BY 1, 2 ORDER BY 1, 2
        """,
    )
    s.append(_table(["year", "source", "events", "decks"], rows))

    s.append("\n## Events and decks by event_type\n")
    rows = _rows(
        conn,
        """
        SELECT coalesce(e.event_type, '(null)'), count(DISTINCT e.id), count(d.id)
        FROM events e LEFT JOIN decks d ON d.event_id = e.id
        GROUP BY 1 ORDER BY 2 DESC, 1
        """,
    )
    s.append(_table(["event_type", "events", "decks"], rows))

    s.append("\n## Unresolved cards\n")
    rows = _rows(
        conn,
        """
        SELECT count(*), coalesce(sum(occurrences), 0), coalesce(sum(decks_affected), 0)
        FROM ingest_unresolved_cards
        """,
    )
    s.append(_table(["distinct unresolved names", "occurrences", "deck-name pairs"], rows))
    top = _rows(
        conn,
        """
        SELECT card_name, occurrences, decks_affected
        FROM ingest_unresolved_cards ORDER BY occurrences DESC, card_name LIMIT 50
        """,
    )
    if top:
        s.append("\nTop unresolved names:\n")
        s.append(_table(["card_name", "occurrences", "decks_affected"], top))

    s.append("\n## Referential integrity\n")
    checks = [
        (
            "decks -> events",
            "SELECT count(*) FROM decks d"
            " LEFT JOIN events e ON e.id=d.event_id WHERE e.id IS NULL",
        ),
        (
            "deck_cards -> decks",
            "SELECT count(*) FROM deck_cards dc"
            " LEFT JOIN decks d ON d.id=dc.deck_id WHERE d.id IS NULL",
        ),
        (
            "deck_cards -> cards",
            "SELECT count(*) FROM deck_cards dc"
            " LEFT JOIN cards c ON c.id=dc.card_id WHERE c.id IS NULL",
        ),
        (
            "events -> formats",
            "SELECT count(*) FROM events e"
            " LEFT JOIN formats f ON f.id=e.format_id WHERE f.id IS NULL",
        ),
        (
            "events -> games",
            "SELECT count(*) FROM events e"
            " LEFT JOIN games g ON g.id=e.game_id WHERE g.id IS NULL",
        ),
        (
            "duplicate (source, source_event_id)",
            "SELECT count(*) FROM (SELECT source, source_event_id FROM events"
            " GROUP BY 1,2 HAVING count(*)>1) t",
        ),
        ("events dated in the future", "SELECT count(*) FROM events WHERE date > current_date"),
        ("deck_cards with count < 1", "SELECT count(*) FROM deck_cards WHERE count < 1"),
    ]
    results = [(name, _rows(conn, sql)[0][0]) for name, sql in checks]
    s.append(_table(["check (orphans/violations)", "count"], results))
    all_ok = all(v == 0 for _, v in results)
    s.append(f"\nAll referential-integrity checks pass: **{all_ok}**")

    s.append("\n## Deck-size distribution (mainboard)\n")
    rows = _rows(
        conn,
        """
        WITH sizes AS (
            SELECT d.id, coalesce(sum(dc.count) FILTER (WHERE dc.board='main'), 0) AS main
            FROM decks d LEFT JOIN deck_cards dc ON dc.deck_id = d.id
            GROUP BY d.id
        )
        SELECT CASE
                 WHEN main = 0 THEN '0'
                 WHEN main < 60 THEN '1-59'
                 WHEN main = 60 THEN '60'
                 WHEN main <= 69 THEN '61-69'
                 WHEN main <= 79 THEN '70-79'
                 WHEN main <= 89 THEN '80-89'
                 ELSE '90+'
               END AS bucket, count(*)
        FROM sizes GROUP BY 1
        ORDER BY min(main)
        """,
    )
    s.append(_table(["mainboard size", "decks"], rows))

    fmt_cfgs = {f.name: f for f in load_formats()}
    rows = _rows(
        conn,
        """
        WITH sizes AS (
            SELECT d.id, f.name AS format,
                   coalesce(sum(dc.count) FILTER (WHERE dc.board='main'), 0) AS main,
                   coalesce(sum(dc.count) FILTER (WHERE dc.board='side'), 0) AS side
            FROM decks d
            JOIN events e ON e.id = d.event_id JOIN formats f ON f.id = e.format_id
            LEFT JOIN deck_cards dc ON dc.deck_id = d.id
            GROUP BY d.id, f.name
        )
        SELECT format, count(*) AS decks,
               count(*) FILTER (WHERE main = 0) AS empty_main,
               count(*) FILTER (WHERE main > 0 AND main < 60) AS undersized_main,
               count(*) FILTER (WHERE side > 15) AS oversized_side
        FROM sizes GROUP BY format ORDER BY format
        """,
    )
    s.append("\nPer-format anomalies vs `formats.config` expectations:\n")
    s.append(_table(["format", "decks", "empty main", "main 1-59", "side >15"], rows))
    for name, *_ in rows:
        cfg = fmt_cfgs.get(name)
        if cfg:
            s.append(
                f"\n(config for `{name}`: expected_mainboard_min="
                f"{cfg.expected_mainboard_min}, expected_sideboard_max="
                f"{cfg.expected_sideboard_max})"
            )

    s.append("\n## Standings coverage (winrate-capable data for M2)\n")
    rows = _rows(
        conn,
        """
        SELECT e.source, e.event_type,
               count(*) FILTER (WHERE d.wins IS NOT NULL) AS decks_with_record,
               count(*) AS decks
        FROM decks d JOIN events e ON e.id = d.event_id
        GROUP BY 1, 2 ORDER BY 1, 2
        """,
    )
    s.append(_table(["source", "event_type", "decks with W/L record", "decks"], rows))
    s.append("")
    return "\n".join(s)
